language: node_js
node_js:
- "9.0.0"

branches:
  only:
  - develop

before_script:
- npm install npm
- npm install -g firebase-tools
- npm install -g @angular/cli

script:
- ionic build --prod

after_success:
- firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change